2024-05-21T22:02:52 {"cpu": 0.2470703125, "cpu_total": 8, "cpu_usage": 0.0308837890625, "memory": 3836.0, "memory_total": 9894.0, "memory_usage": 0.38770972306448354, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 1 in schedule 1 is alive.", "timestamp": 1716328972.517293, "uuid": "593cce5f1a534d27941cd2f7a365da7b"}
2024-05-21T22:02:52 {"cpu": 0.2470703125, "cpu_total": 8, "cpu_usage": 0.0308837890625, "memory": 3852.0, "memory_total": 9894.0, "memory_usage": 0.38932686476652517, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 1 in schedule 1 is alive.", "timestamp": 1716328972.671977, "uuid": "09c05792b724470db8ef374c1174d561"}
2024-05-21T22:02:52 {"block_run_id": 1, "block_uuid": "data_tracker", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 1: pipeline amazon_tracker block data_tracker", "timestamp": 1716328972.762429, "uuid": "83f76aab68174f52a99d42f1f5c9c04c"}
2024-05-21T22:02:53 {"block_run_id": 1, "block_uuid": "data_tracker", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "EXCEPTION", "message": "BlockRun 1 (block_uuid: data_tracker) failed.", "timestamp": 1716328973.63754, "uuid": "86cb1c1ccddd43de9372d5081ac80a13", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1393, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1295, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1617, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1776, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1819, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 97, in load_data_from_file\nNameError: name 'requests' is not defined\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 164, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 776, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 101, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 53, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1641, in schedule_all\n    PipelineScheduler(r).start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 192, in start\n    self.schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 320, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 623, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1177, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 452, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["name 'requests' is not defined"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1393, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1295, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1617, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1776, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1819, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 97, in load_data_from_file
NameError: name 'requests' is not defined
2024-05-21T22:03:02 {"cpu": 0.244140625, "cpu_total": 8, "cpu_usage": 0.030517578125, "memory": 3827.0, "memory_total": 9894.0, "memory_usage": 0.3868000808570851, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 1 in schedule 1 is alive.", "timestamp": 1716328982.811316, "uuid": "305d759219604f6fbd25793556bada77"}
2024-05-21T22:06:02 {"cpu": 0.29296875, "cpu_total": 8, "cpu_usage": 0.03662109375, "memory": 3851.0, "memory_total": 9894.0, "memory_usage": 0.38922579341014757, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 2 in schedule 1 is alive.", "timestamp": 1716329162.673104, "uuid": "906e3da39ee24472a1a5cd6501dda4b8"}
2024-05-21T22:06:02 {"cpu": 0.29296875, "cpu_total": 8, "cpu_usage": 0.03662109375, "memory": 3878.0, "memory_total": 9894.0, "memory_usage": 0.39195472003234283, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 2 in schedule 1 is alive.", "timestamp": 1716329162.814685, "uuid": "8e9209a16ce64ba1bf96de941cf3a3b2"}
2024-05-21T22:06:02 {"block_run_id": 3, "block_uuid": "data_tracker", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 3: pipeline amazon_tracker block data_tracker", "timestamp": 1716329162.84816, "uuid": "fd2221500b9d4f9e9e6a6ac4cec68202"}
2024-05-21T22:06:12 {"cpu": 0.294921875, "cpu_total": 8, "cpu_usage": 0.036865234375, "memory": 4038.0, "memory_total": 9894.0, "memory_usage": 0.40812613705275924, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 2 in schedule 1 is alive.", "timestamp": 1716329172.943277, "uuid": "0f88a7ceed3e4790a51feec7bb260a84"}
2024-05-21T22:06:22 {"cpu": 0.29296875, "cpu_total": 8, "cpu_usage": 0.03662109375, "memory": 4073.0, "memory_total": 9894.0, "memory_usage": 0.4116636345259753, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 2 in schedule 1 is alive.", "timestamp": 1716329182.207661, "uuid": "bf08fbd9f9bf40c88ead39042bcfbae6"}
2024-05-21T22:06:32 {"cpu": 0.30078125, "cpu_total": 8, "cpu_usage": 0.03759765625, "memory": 4073.0, "memory_total": 9894.0, "memory_usage": 0.4116636345259753, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 2 in schedule 1 is alive.", "timestamp": 1716329192.40879, "uuid": "f0fcb4b534df425cbda2a1739c793c8b"}
2024-05-21T22:06:38 {"block_run_id": 3, "block_uuid": "data_tracker", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "BlockRun 3 (block_uuid: data_tracker) completes.", "timestamp": 1716329198.586097, "uuid": "d31cfdd26bc54959b3c52e57c6806e64"}
2024-05-21T22:06:42 {"cpu": 0.302734375, "cpu_total": 8, "cpu_usage": 0.037841796875, "memory": 3846.0, "memory_total": 9894.0, "memory_usage": 0.38872043662825956, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 2 in schedule 1 is alive.", "timestamp": 1716329202.5796, "uuid": "e9531f317c7b4b48b88a0ce1c3e8bb2c"}
2024-05-21T22:06:42 {"block_run_id": 4, "block_uuid": "data_to_fastapi", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Execute PipelineRun 2, BlockRun 4: pipeline amazon_tracker block data_to_fastapi", "timestamp": 1716329202.897628, "uuid": "86a5c489364346de8969554b26196a93"}
2024-05-21T22:06:43 {"block_run_id": 4, "block_uuid": "data_to_fastapi", "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "BlockRun 4 (block_uuid: data_to_fastapi) completes.", "timestamp": 1716329203.787261, "uuid": "608c6fdf1c204ca78902c267da3f1610"}
2024-05-21T22:06:52 {"cpu": 0.302734375, "cpu_total": 8, "cpu_usage": 0.037841796875, "memory": 3841.0, "memory_total": 9894.0, "memory_usage": 0.38821507984637155, "pipeline_run_id": 2, "pipeline_schedule_id": 1, "pipeline_uuid": "amazon_tracker", "hostname": "8f0dd854e41f", "level": "INFO", "message": "Pipeline amazon_tracker for run 2 in schedule 1 is alive.", "timestamp": 1716329212.885602, "uuid": "d4c769782fe84be5aef04d63e387d636"}
